name: Build and publish Forest IAC Docker image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-snapshot-iac-image:
    name: Build Docker Infrastructure image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        if: ${